#colors:
#  # Default colors
#  primary:
#    background: '0x2c2c2c'
#    foreground: '0xb9b9b9'
#
#  # Normal colors
#  normal:
#    black:   '0x101010'
#    red:     '0x7c7c7c'
#    green:   '0x8e8e8e'
#    yellow:  '0xa0a0a0'
#    blue:    '0x0b4685'
#    magenta: '0x747474'
#    cyan:    '0x868686'
#    white:   '0xb9b9b9'
#
#  # Bright colors
#  bright:
#    black:   '0x525252'
#    red:     '0x7c7c7c'
#    green:   '0x8e8e8e'
#    yellow:  '0xa0a0a0'
#    blue:    '0x0b4685'
#    magenta: '0x747474'
#    cyan:    '0x868686'
#    white:   '0xf7f7f7'

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0x6b6b6b'
    green:   '0xc4c4c4'
    yellow:  '0xb3b3b3'
    blue:    '0x999999'
    magenta: '0x717171'
    cyan:    '0x8a8a8a'
    white:   '0xb5cabb'

  # Bright colors
  bright:
    black:   '0x202020'
    red:     '0x464646'
    green:   '0xf8f8f8'
    yellow:  '0xeeeeee'
    blue:    '0x7c7c7c'
    magenta: '0xadadad'
    cyan:    '0xc0c0c0'
    white:   '0x99ac9e'

font:
  normal:
    family: 'FiraCode Nerd Font Mono'
    style: Light 

  bold:
    family: 'FiraCode Nerd Font Mono'
    style: Bold

  italic:
    family: 'FiraCode Nerd Font Mono'
    style: Italic

  bold_italic:
    family: 'FiraCode Nerd Font Mono'
    style: Bold Italic

  size: 11

key_bindings:
  - { key: K, mods: Control, mode: ~Vi|~Search, chars: "\x0c"}
  - { key: K, mods: Control, mode: ~Vi|~Search, action: ClearHistory }
