colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xdddddd'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0x6b6b6b'
    green:   '0xc4c4c4'
    yellow:  '0xb3b3b3'
    blue:    '0x9999ff'
    magenta: '0x717171'
    cyan:    '0x8a8a8a'
    white:   '0xb5bbca'

  # Bright colors
  bright:
    black:   '0x202020'
    red:     '0x464646'
    green:   '0xf8f8f8'
    yellow:  '0xeeeeee'
    blue:    '0x7c7cff'
    magenta: '0xadadad'
    cyan:    '0xc0c0c0'
    white:   '0x999eac'

font:
  normal:
    family: 'FiraCode Nerd Font Mono'
    style: Light 

  bold:
    family: 'FiraCode Nerd Font Mono'
    style: Bold

  italic:
    family: 'FiraCode Nerd Font Mono'
    style: Italic

  bold_italic:
    family: 'FiraCode Nerd Font Mono'
    style: Bold Italic

  size: 9

key_bindings:
  - { key: K, mods: Control, mode: ~Vi|~Search, chars: "\x0c"}
  - { key: K, mods: Control, mode: ~Vi|~Search, action: ClearHistory }
